using MediatR;
using MyWedding.Domain.Entities;
using MyWedding.Domain.Interfaces;
using MyWedding.SharedKernel.Exceptions;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace MyWedding.Vendors.Application.Features.Inquiries.Commands.GenerateInquiryQuote
{
    public class GenerateInquiryQuoteCommandHandler : IRequestHandler<GenerateInquiryQuoteCommand, InquiryQuoteResultDto>
    {
        private readonly IVendorInquiryRepository _inquiryRepository;
        private readonly IVendorInquiryQuoteRepository _quoteRepository;
        private readonly IVendorRepository _vendorRepository;
        private readonly IUnitOfWork _unitOfWork;

        public GenerateInquiryQuoteCommandHandler(
            IVendorInquiryRepository inquiryRepository,
            IVendorInquiryQuoteRepository quoteRepository,
            IVendorRepository vendorRepository,
            IUnitOfWork unitOfWork)
        {
            _inquiryRepository = inquiryRepository;
            _quoteRepository = quoteRepository;
            _vendorRepository = vendorRepository;
            _unitOfWork = unitOfWork;
        }

        public async Task<InquiryQuoteResultDto> Handle(
            GenerateInquiryQuoteCommand request,
            CancellationToken cancellationToken)
        {
            var inquiry = await _inquiryRepository.GetByIdForVendorAsync(
                request.InquiryId,
                request.VendorId,
                cancellationToken);

            if (inquiry is null)
            {
                throw new NotFoundException($"Inquiry '{request.InquiryId}' was not found.");
            }

            var vendor = await _vendorRepository.GetByIdAsync(request.VendorId, cancellationToken);
            var businessName = vendor?.BusinessName ?? "Our studio";
            var amount = request.ProposedAmount ?? 385_000m;
            var reference = $"Q-{DateTime.UtcNow:yyyyMMdd}-{Guid.NewGuid().ToString("N")[..6].ToUpperInvariant()}";
            var pdfKey = $"quotes/{request.VendorId}/{reference}.pdf";

            var body = $"""
                Official Quote — {reference}
                Vendor: {businessName}
                Amount: LKR {amount:N0}
                Valid for 14 days from issue date.

                This document is generated by MyWedding.lk for {inquiry.SenderEmail}.
                """;

            var quote = new VendorInquiryQuote
            {
                Id = Guid.NewGuid(),
                InquiryId = inquiry.Id,
                VendorId = request.VendorId,
                QuoteReference = reference,
                Amount = amount,
                Currency = "LKR",
                Body = body,
                PdfStorageKey = pdfKey,
                CreatedAt = DateTime.UtcNow
            };

            await _quoteRepository.AddAsync(quote, cancellationToken);
            await _unitOfWork.SaveChangesAsync(cancellationToken);

            var eventLabel = inquiry.Subject ?? "your event";
            var suggestedReply = $"""
                Dear {inquiry.SenderEmail.Split('@')[0]},

                Thank you for your inquiry. Based on your requirements, we propose our package at LKR {amount:N0} (Quote ref: {reference}).

                Attached: official quote PDF ({pdfKey}).

                Warm regards,
                {businessName}
                """;

            return new InquiryQuoteResultDto
            {
                QuoteId = quote.Id,
                QuoteReference = reference,
                Amount = amount,
                Currency = "LKR",
                SuggestedReply = suggestedReply,
                PdfStorageKey = pdfKey
            };
        }
    }
}
