using MyWedding.SharedKernel.Interfaces;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MyWedding.Infrastructure.Services;

public class InquiryQuotePdfGenerator : IQuotePdfGenerator
{
    static InquiryQuotePdfGenerator()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public byte[] Generate(InquiryQuotePdfModel model)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.MarginHorizontal(48);
                page.MarginVertical(40);
                page.DefaultTextStyle(x => x.FontSize(11).FontColor(Colors.Grey.Darken3));

                page.Header().Column(column =>
                {
                    column.Item().Row(row =>
                    {
                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Text("Official quote")
                                .FontSize(22)
                                .Bold()
                                .FontColor(Colors.Blue.Darken3);
                            col.Item().Text(model.QuoteReference)
                                .FontSize(10)
                                .FontColor(Colors.Grey.Medium);
                        });
                        row.ConstantItem(120).AlignRight().Column(col =>
                        {
                            col.Item().Text("MyWedding.lk")
                                .Bold()
                                .FontColor(Colors.Blue.Medium);
                            col.Item().Text(DateTime.UtcNow.ToString("dd MMM yyyy"))
                                .FontSize(9)
                                .FontColor(Colors.Grey.Medium);
                        });
                    });
                    column.Item().PaddingTop(8).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                });

                page.Content().PaddingTop(24).Column(column =>
                {
                    column.Spacing(16);

                    column.Item().Background(Colors.Blue.Lighten5).Padding(16).Column(box =>
                    {
                        box.Item().Text($"{model.Currency} {model.Amount:N0}")
                            .FontSize(28)
                            .Bold()
                            .FontColor(Colors.Blue.Darken3);
                        box.Item().Text("Proposed package total")
                            .FontSize(10)
                            .FontColor(Colors.Grey.Darken1);
                    });

                    column.Item().Row(row =>
                    {
                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Text("Vendor").FontSize(9).Bold().FontColor(Colors.Grey.Medium);
                            col.Item().Text(model.VendorName).FontSize(13).Bold();
                        });
                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Text("Prepared for").FontSize(9).Bold().FontColor(Colors.Grey.Medium);
                            col.Item().Text(model.PlannerDisplayName).FontSize(13).Bold();
                            col.Item().Text(model.PlannerBusinessName).FontSize(10);
                        });
                    });

                    if (!string.IsNullOrWhiteSpace(model.EventName))
                    {
                        column.Item().Column(col =>
                        {
                            col.Item().Text("Event").FontSize(9).Bold().FontColor(Colors.Grey.Medium);
                            col.Item().Text(model.EventName).FontSize(12);
                        });
                    }

                    column.Item().Column(col =>
                    {
                        col.Item().Text("Recipient").FontSize(9).Bold().FontColor(Colors.Grey.Medium);
                        col.Item().Text(model.RecipientEmail).FontSize(11);
                    });

                    column.Item().PaddingTop(8).Column(col =>
                    {
                        col.Item().Text("Quote details").FontSize(11).Bold();
                        col.Item().PaddingTop(6).Text(model.QuoteBody).LineHeight(1.4f);
                    });

                    column.Item().PaddingTop(12).Text(
                            "This quote is valid for 14 days from the issue date. " +
                            "Generated by MyWedding.lk on behalf of the vendor and planning partner.")
                        .FontSize(9)
                        .Italic()
                        .FontColor(Colors.Grey.Medium);
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Page ");
                    text.CurrentPageNumber();
                    text.Span(" of ");
                    text.TotalPages();
                });
            });
        });

        return document.GeneratePdf();
    }
}
